<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1.1", {packages:["table"]});
    google.setOnLoadCallback(drawStuff);

    function drawStuff() {
var data = new google.visualization.arrayToDataTable(<?php echo Mage::helper('core')->jsonEncode($this->getReport()->arrayToDataTable()); ?>);
console.log(data);
        var options = {
            width: 900,
            chart: {
                title: 'Nearby galaxies',
                subtitle: 'distance on the left, brightness on the right'
            },
            bars: 'horizontal', // Required for Material Bar Charts.
            series: {
                0: { axis: 'distance' }, // Bind series 0 to an axis named 'distance'.
                1: { axis: 'brightness' } // Bind series 1 to an axis named 'brightness'.
            },
            axes: {
                x: {
                    distance: {label: 'parsecs'}, // Bottom x-axis.
                    brightness: {side: 'top', label: 'apparent magnitude'} // Top x-axis.
                }
            }
        };

        var chart = new google.visualization.Table(document.getElementById('<?php echo $this->getReport()->getUniqueId(); ?>'));
        chart.draw(data, options);
    };
</script>

<?php
//Zend_Debug::dump(Mage::helper('core')->jsonEncode($this->getReport()->arrayToDataTable()));
?>
<div id="<?php echo $this->getReport()->getUniqueId(); ?>" style="width: 900px; height: 500px;"></div>